### ISSUE TITLE
 Fetching an imageless anime throws IndexError

### ISSUE THREAD

**Issue by junpet** [JohnDoee/malparser#2]
Reproduce:
```python
from malparser import MAL
mal = MAL()
a = mal.get_anime(40651)
a.fetch()
```
---

Result is:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "\venv\lib\site-packages\malparser\base.py", line 30, in fetch
    return self.mal._fetch(self)
  File "\venv\lib\site-packages\malparser\mal.py", line 34, in _fetch
    obj.parse(data)
  File "\venv\lib\site-packages\malparser\anime.py", line 17, in parse
    super(Anime, self).parse(html)
  File "\venv\lib\site-packages\malparser\base.py", line 46, in parse
    cover = schema.xpath('.//img[@itemprop="image"]')[0]
IndexError: list index out of range
```
---

Tested on these systems:
Microsoft Windows [Version 10.0.18362.418]
Python 3.8.0

Debian 10 (buster)
Python 3.7.30

---

You should check the existence of the elements before getting the first one of it (`[0]`).

**Comment by JohnDoee** [comment]
> You should check the existence of the elements before getting the first one of it ([0]).

I tried to go through my assumptions in the code and see if they aligned with what can be expected from MyAnimeList. Fixed the cover bug and found another one.

Version 1.1.7 should be able to parse the latest entries I could find on MAL.
